### ISSUE TITLE
请教一下，若宿主机本身有mongodb + leanote，如何直连宿主mongo

### ISSUE THREAD

**Issue by zzzmhcn** [hjh142857/docker_leanote_x86_64#1]
因为我本身机器就用了很久的leanote + mongodb
最近希望把内容迁移进docker
不知道我理解的对不对
您的这个镜像中包含了mongodb
我想是否可以再出一个不含db的版本的docker，配置参数的时候加上--link mongo
当然我其实刚开始学docker
这只是一个不成熟的小建议
以上

**Comment by hjh142857** [comment]
我也刚玩docker，菜的很。。不过并不准备再弄一个不含db的版本，写readme太累了，而且还要单独安装mongo client来实现导入导出数据库、清空表的功能。。不过你可以自己fork一下然后简单的修改代码来实现，缺点是还是安装了mongo而不是client内存不会多占用但空间多使用几十兆，大概思路如下：
* 1、Dockerfile中ENV部分增加DBHOST等一系列db相关的变量的定义。docker目录下/data/leanote/conf/app.conf中有关于mongodb的配置。
* 2、在entrypoint.sh中参考19-21行使用sed修改app.conf中关于db的配置
* 3、entrypoint.sh中auto backup前加一句`pkill mongodb`关掉mongo，然后修改一下mongodump和mongorestore命令里的地址参数（如果有用户名自己加）。

**Comment by zzzmhcn** [comment]
恩恩，感谢回复，我试试，谢啦
