### ISSUE TITLE
多平台客户端无法同步笔记里的图片

### ISSUE THREAD

**Issue by siyuanfeng000** [hjh142857/docker_leanote_x86_64#2]
siteurl使用服务器ip+端口的模式，多平台的客户端还是无法同步图片

**Comment by hjh142857** [comment]
请把问题描述的更清楚一些，通过你的描述我无法获取有用的信息。
1、什么客户端上传，在这个客户端上进入编辑模式显示的图片链接是什么？
2、不能同步图片的是哪个客户端，看不了图的时候进入编辑状态上面的链接是什么？
3、[宿主机储存路径]/leanotedata/leanote/file下是否有你上传的图片？

**Comment by siyuanfeng000** [comment]
已经解决了，siteurl必须要加上http://

**Comment by hjh142857** [comment]
OK，感谢反馈，晚点我修改下readme注明一下
