### ISSUE TITLE
db映射宿主

### ISSUE THREAD

**Issue by molezz** [hjh142857/docker_leanote_x86_64#3]
看了下， 是否-v /host/leanotedata/db:/data/db 设置，即可将数据库放在宿主上，备份还原时用这个文件夹也可以。 就不用restore和back

**Comment by hjh142857** [comment]
可以尝试下，我记得我当时试的时候db映射有一点bug，似乎是映射不出来（不太确定）。后来懒得折腾就直接数据库和程序目录备份还原一把梭了
